[package]
name = "training"
version = "0.1.0"
edition = "2021"


[dependencies]
bullet = { git = "https://github.com/jw1912/bullet", package = "bullet_lib", features = ["hip"], default-features = false }

[[bin]]
name = "training"
path = "training.rs"


